-- Pregunta 1: Volumen y distribución de solicitudes
-- Resumen mensual del año 2024, por mes y categoría
-- Herramienta utilizada: BigQuery

WITH DETALLE AS (
SELECT DATE_TRUNC(A.FECHA_SOLICITUD, MONTH) MES,
       B.CATEGORIA,
       COUNT(DISTINCT A.ID_SOLICITUD) TOTAL_SOL_RECIBIDAS,
       COUNT(DISTINCT IF(A.ESTADO = 'Aprobado', A.ID_SOLICITUD, NULL)) TOTAL_SOL_APROBADAS,
       COUNT(DISTINCT IF(A.ESTADO = 'Rechazado', A.ID_SOLICITUD, NULL)) TOTAL_SOL_RECHAZADAS,
       COUNT(DISTINCT IF(A.ESTADO = 'En Proceso', A.ID_SOLICITUD, NULL)) TOTAL_SOL_EN_PROCESO
  FROM `first-project-500415.data_maestra_prueba.solicitudes_material` A
  LEFT JOIN `first-project-500415.data_maestra_prueba.categorias` B
    ON A.ID_CATEGORIA = B.ID_CATEGORIA
 WHERE EXTRACT(YEAR FROM A.FECHA_SOLICITUD) = 2024
  GROUP BY DATE_TRUNC(A.FECHA_SOLICITUD, MONTH), B.CATEGORIA
)
SELECT MES, CATEGORIA, TOTAL_SOL_RECIBIDAS, TOTAL_SOL_APROBADAS, TOTAL_SOL_RECHAZADAS, TOTAL_SOL_EN_PROCESO, ROUND(SAFE_DIVIDE(TOTAL_SOL_APROBADAS, TOTAL_SOL_RECIBIDAS)*100, 2) PCT_APROBACION
  FROM DETALLE
 ORDER BY MES, TOTAL_SOL_RECIBIDAS DESC;
