-- Pregunta 3: Ranking de aprobadores por desempeño
-- Herramienta utilizada BigQuery

WITH DETALLE AS (
SELECT B.NOMBRE_COMPLETO NOMBRE_APROBADOR,
       B.AREA AREA_APROBADOR,
       COUNT(DISTINCT A.ID_SOLICITUD) TOTAL_SOL_GESTIONADAS,
       COUNT(DISTINCT IF(A.ESTADO = 'Aprobado', A.ID_SOLICITUD, NULL)) TOTAL_SOL_APROBADAS,
       COUNT(DISTINCT IF(A.ESTADO = 'Rechazado', A.ID_SOLICITUD, NULL)) TOTAL_SOL_RECHAZADAS,
       ROUND(AVG(A.DIAS_CICLO), 2) PROM_DIAS_CICLO
  FROM `first-project-500415.data_maestra_prueba.solicitudes_material` A
  LEFT JOIN `first-project-500415.data_maestra_prueba.usuarios` B
    ON A.ID_SOLICITANTE = B.ID_USUARIO
  GROUP BY B.NOMBRE_COMPLETO, B.AREA
),
CALC_PCT_APROB AS (
  SELECT NOMBRE_APROBADOR,
         AREA_APROBADOR,
         TOTAL_SOL_GESTIONADAS,
         TOTAL_SOL_APROBADAS,
         TOTAL_SOL_RECHAZADAS,
         ROUND(SAFE_DIVIDE(TOTAL_SOL_APROBADAS, TOTAL_SOL_GESTIONADAS)*100, 2) PCT_APROBACION,
         PROM_DIAS_CICLO
    FROM DETALLE
)
SELECT NOMBRE_APROBADOR,
       AREA_APROBADOR,
       TOTAL_SOL_GESTIONADAS,
       TOTAL_SOL_APROBADAS,
       TOTAL_SOL_RECHAZADAS,
       PCT_APROBACION,
       PROM_DIAS_CICLO,
       ROW_NUMBER() OVER (
        PARTITION BY AREA_APROBADOR
        ORDER BY PCT_APROBACION DESC
       ) RANKING
  FROM CALC_PCT_APROB;
  