-- Pregunta 4: Análisis de tiempos por etapa del proceso
-- Descompón el tiempo total del ciclo en las tres etapas del proceso y calcula para cada categoría

WITH DETALLE AS (
SELECT B.CATEGORIA,
       A.FECHA_SOLICITUD,
       A.FECHA_VALIDACION_DATOS,
       A.FECHA_REVISION_CALIDAD,
       A.FECHA_APROBACION_REGULATORIA,
       A.FECHA_CIERRE
  FROM `first-project-500415.data_maestra_prueba.solicitudes_material` A
  LEFT JOIN `first-project-500415.data_maestra_prueba.categorias` B
    ON A.ID_CATEGORIA = B.ID_CATEGORIA
),
ETAPA_1 AS (
  SELECT CATEGORIA,
         AVG(DATE_DIFF(FECHA_VALIDACION_DATOS, FECHA_SOLICITUD, DAY)) T_PROM_ETAPA_1
    FROM DETALLE
   WHERE FECHA_VALIDACION_DATOS IS NOT NULL
     AND FECHA_SOLICITUD IS NOT NULL
   GROUP BY CATEGORIA
),
ETAPA_2 AS (
  SELECT CATEGORIA,
         AVG(DATE_DIFF(FECHA_REVISION_CALIDAD, FECHA_VALIDACION_DATOS, DAY)) T_PROM_ETAPA_2
    FROM DETALLE
   WHERE FECHA_REVISION_CALIDAD IS NOT NULL
     AND FECHA_VALIDACION_DATOS IS NOT NULL
   GROUP BY CATEGORIA
),
ETAPA_3 AS (
  SELECT CATEGORIA,
         AVG(DATE_DIFF(FECHA_APROBACION_REGULATORIA, FECHA_REVISION_CALIDAD, DAY)) T_PROM_ETAPA_3
    FROM DETALLE
   WHERE FECHA_APROBACION_REGULATORIA IS NOT NULL
     AND FECHA_REVISION_CALIDAD IS NOT NULL
   GROUP BY CATEGORIA
),
PTOM_TOTAL AS (
  SELECT CATEGORIA,
         AVG(DATE_DIFF(FECHA_CIERRE, FECHA_SOLICITUD, DAY)) T_PROM_TOTAL
    FROM DETALLE
   WHERE FECHA_CIERRE IS NOT NULL
     AND FECHA_SOLICITUD IS NOT NULL
   GROUP BY CATEGORIA
)
SELECT A.CATEGORIA,
       ROUND(A.T_PROM_ETAPA_1, 2) T_PROM_ETAPA_1,
       ROUND(B.T_PROM_ETAPA_2, 2) T_PROM_ETAPA_2,
       ROUND(C.T_PROM_ETAPA_3, 2) T_PROM_ETAPA_3,
       ROUND(D.T_PROM_TOTAL, 2) T_PROM_TOTAL,
       CASE
         WHEN A.T_PROM_ETAPA_1 >= B.T_PROM_ETAPA_2 AND A.T_PROM_ETAPA_1 >= C.T_PROM_ETAPA_3 THEN 'VALIDACIÓN DE DATOS'
         WHEN B.T_PROM_ETAPA_2 >= A.T_PROM_ETAPA_1 AND B.T_PROM_ETAPA_2 >= C.T_PROM_ETAPA_3 THEN 'REVISIÓN DE CALIDAD'
         ELSE 'APROBACIÓN REGULATORIA'
       END ETAPA_MAS_LENTA
  FROM ETAPA_1 A
  LEFT JOIN ETAPA_2 B
    ON A.CATEGORIA = B.CATEGORIA
  LEFT JOIN ETAPA_3 C
    ON A.CATEGORIA = C.CATEGORIA
  LEFT JOIN PTOM_TOTAL D
    ON A.CATEGORIA = D.CATEGORIA




